name: Backend CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    env:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Create Firebase service account key file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > serviceAccountKey.json
      - name: Run tests
        run: npm test
      - name: Run Firestore connection test
        run: npm run firestore-test
